version: "3.0"

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  backend:
    build: ./api
    environment:
      - POSTGRES_PASSWORD=password
      - SANIC_AUTORELOAD=true
    volumes:
      - ./api:/srv/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
      - frontend
  frontend:
    build:
      context: ./client
      args:
        NODE_ENV: "development"
    volumes:
      - ./client:/srv/app
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  backend:
  frontend:
